version: '2'
services:
    jmojobs-app:
        image: jmojobs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jmojobs-mysql:3306/jmojobs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jmojobs-elasticsearch:9300
        ports:
            - 8080:8080
    jmojobs-mysql:
        extends:
            file: mysql.yml
            service: jmojobs-mysql
    jmojobs-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jmojobs-elasticsearch
